import Head from "next/head";
import Image from "next/image";
import { useRecoilValue } from "recoil";
import sidebarState from "../atoms/SidebarState";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Products from "../components/Products";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
  const open = useRecoilValue(sidebarState);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="">
        {open ? <Sidebar /> : ""}

        {/* Navbar */}
        <div className="">
          <Navbar />
        </div>
        <div className="px-4 sm:px-7  ">
          {/* Hero */}
          <Hero />
          {/* Producst */}
          <Products />
        </div>
      </div>
    </div>
  );
}
